import { NextRequest, NextResponse } from 'next/server'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  // Create a mock download response
  const mockFileContent = `This is a mock download for file ID: ${id}
  
Generated by Stock Media SaaS Mock System
File Type: Stock Media
Status: Mock Download (External API Unavailable)
Date: ${new Date().toISOString()}

This is a placeholder file. In production, this would be the actual downloaded file.
The external Nehtw API is currently unavailable, so this mock response is provided.

For real downloads, please ensure the external API is properly configured.`

  return new NextResponse(mockFileContent, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': `attachment; filename="mock-download-${id}.txt"`,
      'Cache-Control': 'no-cache'
    }
  })
}
